### PR TITLE
Feature/move jscs rules to eslint

### PR DESCRIPTION
**Pull request by delacruz-dev**
**_warning: unfinished**_

I want to have only a single process to validate my JS files, and I think eslint is the best match. My purpose is to match all the rules in JSCS to ESLINT. There is a single commit per rule, to allow you to understand the rule replacement.

### CODE REVIEW

**Comment by carlosvillu** [comment]
But JSCS and ESLint are different thing.

**Comment by delacruz-dev** [comment]
@carlosvillu why? I'v always been told that JSCS is for coding style and eslint for detecting potential bugs in your code, but eslint has also coding style rules. I would prefer to have all the JS pre commit rules under one single tool, if possible. http://www.sitepoint.com/comparison-javascript-linting-tools/

**Comment by carlosvillu** [comment]
Ok, then we can remove JSCS isnt ?!

**Comment by delacruz-dev** [comment]
I think we can, let me find if all the JSCS rules have a corresponding mapping in eslint, I'm convinced we can :)

**Pull request closed without merging**
